services:
  sonarr:
    #https://docs.linuxserver.io/images/docker-sonarr/#docker-compose-recommended-click-here-for-more-info
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - $HOME/.config/sonarr:/config
      - /pool-1/ds-1/video/tv:/tv #optional
      - /pool-1/ds-1/downloads:/downloads #optional
      - /pool-1/ds-1/:/pool-1/ds-1/
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    #https://docs.linuxserver.io/images/docker-radarr/#media-folders
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - $HOME/.config/radarr:/config
      - /pool-1/ds-1/video/movies:/movies #optional
      - /pool-1/ds-1/downloads:/downloads #optional
      - /pool-1/ds-1/:/pool-1/ds-1/
    ports:
      - 7878:7878
    restart: unless-stopped
  sabnzbd:
    #https://docs.linuxserver.io/images/docker-sabnzbd/#docker-compose-recommended-click-here-for-more-info
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - $HOME/.config/sabnzbd:/config
      - /pool-1/ds-1/downloads:/downloads #optional
      - /pool-1/ds-1/:/pool-1/ds-1/
      - /pool-1/ds-1/incomplete-downloads:/incomplete-downloads #optional
    ports:
      - 8080:8080
    restart: unless-stopped
  plex:
    #https://docs.linuxserver.io/images/docker-plex/#docker-compose-recommended-click-here-for-more-info
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - $HOME/.config/plex:/config
      - /pool-1/ds-1/video/tv:/tv
      - /pool-1/ds-1/video/movies:/movies
      - /mnt:/mnt
    restart: unless-stopped
  lidarr:
    #https://docs.linuxserver.io/images/docker-radarr/#media-folders
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - $HOME/.config/lidarr:/config
      - /pool-1/ds-1/music:/music #optional
      - /pool-1/ds-1/downloads:/downloads #optional
      - /mnt:/mnt
    ports:
      - 8686:8686
    restart: unless-stopped
